### ISSUE TITLE
display project icon

### ISSUE THREAD

**Issue by warengonzaga** [web3phl/directory#23]
### 🤔 Not Existing Feature Request?

- [X] Yes, I'm sure, this is a new requested feature!

### 🤔 Not an Idea or Suggestion?

- [X] Yes, I'm sure, this is not idea or suggestion!

### 📋 Request Details

Instead of showing the default placeholder, it should display the icon from the API data provided.

### 📜 Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/web3phl/directory/blob/main/CODE_OF_CONDUCT.md).

**Comment by warengonzaga** [comment]
@jnebab I guess you can handle this?

**Comment by jnebab** [comment]
parang lahat ng projects. same yung image url

**Comment by warengonzaga** [comment]
> parang lahat ng projects. same yung image url

We are facing a problem in fetching the images from the API.

**Comment by warengonzaga** [comment]
Closing this now! #28
