### ISSUE TITLE
404 on card click (PandoProject)

### ISSUE THREAD

**Issue by kquirapas** [web3phl/directory#34]
### 🤔 Not Existing Bug?

- [X] Yes, I'm sure that this is a bug!

### 👀 Current Behavior

It's 404 on card click

### 🎯 Expected Behavior

Should redirect to entity site

### 📜 Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/web3phl/directory/blob/main/CODE_OF_CONDUCT.md).

**Comment by itsnalla** [comment]
@kquirapas maybe dahil ata sa json file walang https yung pando project sa API. www.pandoproject.org yung nakalagay.

**Comment by itsnalla** [comment]
thoughts also on Royal Labs walang naka indicate na website nila kaya hindi nag reredirect.

**Comment by kquirapas** [comment]
sabay natin sa next milestone @warengonzaga @itsnalla

**Comment by itsnalla** [comment]
we need to standardize din yung form, requirements talaga na may website section kahit anong link lang ilagay nila for example twitter or facebook pag walang website.

**Comment by jnebab** [comment]
I'll fix this on my next PR. i'll include all social links on a larger preview onCardClick so viewers can have other options pag di gumana yung iba. and I agree wth @itsnalla,  di pwedeng walang kahit isang link sa signup. kasi anung point na magpapalagay ka sa directory if you dont provide any links to contact you diba hehe. at least make website url and 1 social media link as required siguro.

**Comment by warengonzaga** [comment]
Please tag this issue on any PR you made folks. 🤝
Thank you for reporting!

**Comment by kquirapas** [comment]
@itsnalla Kindly edit your comments (just like I did) to make it full english so our international contributors can easily contribute. Thank you!

**Comment by itsnalla** [comment]
> @itsnalla Kindly edit your comments (just like I did) to make it full english so our international contributors can easily contribute. Thank you!

edited thanks for correcting bro.

**Comment by warengonzaga** [comment]
Let's prioritize the fix for this thanks!

**Comment by kquirapas** [comment]
@jnebab @itsnalla fixing this on the api either remove or change ko both RoyalLabs and PandoProject

**Comment by kquirapas** [comment]
Resolved. https://github.com/web3phl/directory-api/pull/5

**Comment by kquirapas** [comment]
Will close on merge to main

**Comment by warengonzaga** [comment]
Closing this now as the issue fixed on the [directory-api](https://github.com/web3phl/directory-api) repo.
