### ISSUE TITLE
add pagination

### ISSUE THREAD

**Issue by warengonzaga** [web3phl/directory#41]
### 🤔 Not Existing Feature Request?

- [X] Yes, I'm sure, this is a new requested feature!

### 🤔 Not an Idea or Suggestion?

- [X] Yes, I'm sure, this is not idea or suggestion!

### 📋 Request Details

It's a good thing to have a pagination feature in our growing list of projects.
Kindly read [Pagination Ideas](https://github.com/web3phl/directory/discussions/29) to learn more about the requirements and scope of this feature. We'll update any info here as we have updated info in the discussion section.

### 📜 Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/web3phl/directory/blob/main/CODE_OF_CONDUCT.md).

**Comment by warengonzaga** [comment]
Are you going to take this? @jnebab

**Comment by jnebab** [comment]
anyone can take this. still occupied atm

**Comment by warengonzaga** [comment]
Merged to #35
