### ISSUE TITLE
readme banner

### ISSUE THREAD

**Issue by warengonzaga** [web3phl/directory#46]
### 🤔 Not Existing Feature Request?

- [X] Yes, I'm sure, this is a new requested feature!

### 🤔 Not an Idea or Suggestion?

- [X] Yes, I'm sure, this is not idea or suggestion!

### 📋 Request Details

Nice to have a readme banner too in our readme. Just an inspiration like my other projects below.
https://gathertown.js.org and https://buymeacoffee.js.org### 

![image](https://user-images.githubusercontent.com/15052701/185760715-aa22bad9-d4eb-4d18-afdd-d91ef3dfe1db.png)

### 📜 Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/web3phl/directory/blob/main/CODE_OF_CONDUCT.md).

**Comment by warengonzaga** [comment]
@kquirapas do you think you can handle the design of the banner?

**Comment by kquirapas** [comment]
@warengonzaga sure whats the dimensions?

**Comment by warengonzaga** [comment]
> @warengonzaga sure whats the dimensions?

You can refer to this as an example
https://github.com/warengonzaga/buymeacoffee.js/tree/main/.github

Same setup as well.

**Comment by kquirapas** [comment]
Added on [this commit](https://github.com/web3phl/directory/commit/b5b777ada37ecf3bac1c923cc15f639ae6bdec61). Closing

**Comment by warengonzaga** [comment]
I would suggest always using "Web3" instead of "Web 3" because these are different things. Web 3.0 is a different thing too. cc: @kquirapas

**Comment by warengonzaga** [comment]
The banner is already in use in the main branch so considering to close this issue now.
