### ISSUE TITLE
limit tags to 3 and up to 5 max only

### ISSUE THREAD

**Issue by warengonzaga** [web3phl/directory#47]
### Discussed in https://github.com/web3phl/directory/discussions/30

We've decided to limit the tags to 3 and max only 5.

cc: @itsnalla @jnebab @kquirapas

**Comment by kquirapas** [comment]
@warengonzaga @itsnalla @jnebab 

Lets finalize tags on the discussion below then we can start working on this issue


https://github.com/web3phl/directory/discussions/30

**Comment by jnebab** [comment]
can we provide them a set of tags they can choose from instead of letting them come up with the tags themselves during signup?

**Comment by kquirapas** [comment]
We should finalize tags in #30 today @warengonzaga @jnebab @itsnalla

**Comment by kquirapas** [comment]
@itsnalla check latest comment here https://github.com/web3phl/directory/discussions/30

and update API JSON

**Comment by itsnalla** [comment]
> @itsnalla check latest comment here #30
> 
> and update API JSON
updating atm, will create a PR asap

**Comment by warengonzaga** [comment]
@kquirapas @itsnalla is this all good?

**Comment by itsnalla** [comment]
> @kquirapas @itsnalla is this all good?

all good brother.

**Comment by warengonzaga** [comment]
I mean all the tags are limited to max 5? @itsnalla

**Comment by warengonzaga** [comment]
I can close this now as all the items in #35 are limited to 5 max tags.
